blank_issues_enabled: false
contact_links:
  - name: "📖 Documentation"
    url: https://github.com/jorik41/hassio-ecoflow-cloud/blob/work/README.md
    about: Check the README for setup instructions and device compatibility
  - name: "💬 Discussions"
    url: https://github.com/jorik41/hassio-ecoflow-cloud/discussions
    about: Ask questions and discuss with the community
  - name: "🔧 Contribution Guide"
    url: https://github.com/jorik41/hassio-ecoflow-cloud/blob/work/docs/Contribution.md
    about: Learn how to contribute to the project
